#!/usr/bin/env node
/**
 * Import the hasaneyldrm/exercises-dataset (1,324 exercises with GIF demos)
 * as a new exercise source for EaseurWorkout.
 *
 * - Exercise DATA (names, muscles, instructions): MIT License — free to use.
 * - Exercise MEDIA (GIFs/images): © Gym visual — gymvisual.com — requires
 *   attribution and 180×180 resolution limit per NOTICE.md.
 *
 * Output: src/data/openGymExercises.ts
 */
import { writeFileSync } from "node:fs";

const DATASET_URL =
  "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/data/exercises.json";
const MEDIA_BASE =
  "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main";

console.log("Fetching exercise dataset...");
const data = await fetch(DATASET_URL).then((r) => {
  if (!r.ok) throw new Error(`Fetch failed: ${r.status}`);
  return r.json();
});
console.log(`Loaded ${data.length} exercises`);

// Map dataset targets to our canonical muscle IDs
const TARGET_MAP = {
  delts: "lateral-deltoid",
  abs: "rectus-abdominis",
  quads: "quadriceps",
  lats: "latissimus-dorsi",
  calves: "gastrocnemius",
  pectorals: "pectoralis-major-sternal",
  glutes: "gluteus-maximus",
  hamstrings: "hamstrings",
  adductors: "adductors",
  triceps: "triceps-brachii",
  biceps: "biceps-brachii",
  "upper back": "rhomboids",
  spine: "erector-spinae",
  traps: "trapezius",
  forearms: "brachioradialis",
  abductors: "gluteus-medius",
  "serratus anterior": "obliques",
  "levator scapulae": "trapezius",
  "cardiovascular system": null, // skip cardio
};

// Map dataset equipment
const EQUIP_MAP = {
  "body weight": "Bodyweight",
  cable: "Cable",
  "leverage machine": "Machine",
  assisted: "Machine",
  "medicine ball": "Medicine ball",
  "stability ball": "Stability ball",
  band: "Resistance band",
  barbell: "Barbell",
  rope: "Cable",
  dumbbell: "Dumbbells",
  "ez barbell": "EZ bar",
  "sled machine": "Machine",
  kettlebell: "Kettlebell",
  "olympic barbell": "Barbell",
  weighted: "Bodyweight",
  "resistance band": "Resistance band",
  roller: "Foam roller",
  hammer: "Dumbbells",
  "smith machine": "Machine",
  "trap bar": "Trap bar",
};

const DIFF_BY_EQUIPMENT = {
  "body weight": "beginner",
  band: "beginner",
  "resistance band": "beginner",
  dumbbell: "beginner",
  cable: "intermediate",
  barbell: "intermediate",
  "ez barbell": "intermediate",
  "leverage machine": "beginner",
  "olympic barbell": "advanced",
  "smith machine": "intermediate",
  kettlebell: "intermediate",
};

const exercises = [];

for (const ex of data) {
  const target = TARGET_MAP[ex.target];
  if (target === null) continue; // skip cardio
  if (!target) continue; // unmapped

  const instructions = ex.instructions?.en ?? "";
  const steps = ex.instruction_steps?.en ?? [];

  exercises.push({
    id: `og-${ex.id}`,
    name: ex.name.split(" ").map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(" "),
    primaryMuscles: [target],
    secondaryMuscles: (ex.secondary_muscles ?? [])
      .map((m) => TARGET_MAP[m])
      .filter((m) => m && m !== target)
      .slice(0, 3),
    difficulty: DIFF_BY_EQUIPMENT[ex.equipment] ?? "intermediate",
    equipment: [EQUIP_MAP[ex.equipment] ?? ex.equipment],
    summary: instructions.slice(0, 200) + (instructions.length > 200 ? "…" : ""),
    keyCue: steps[0] ?? instructions.split(".")[0] ?? "",
    steps: steps.length ? steps : instructions.split(". ").filter(Boolean).slice(0, 5),
    tips: [],
    openGymId: ex.id,
    openGymGif: ex.gif_url ? `${MEDIA_BASE}/${ex.gif_url}` : null,
    openGymImage: ex.image ? `${MEDIA_BASE}/${ex.image}` : null,
    openGymAttribution: ex.attribution ?? "© Gym visual — https://gymvisual.com/",
  });
}

console.log(`Mapped ${exercises.length} exercises (skipped ${data.length - exercises.length} cardio/unmapped)`);

const ts = `/**
 * GENERATED by scripts/import-opengym.mjs — do not edit by hand.
 * Exercise data from hasaneyldrm/exercises-dataset (MIT License).
 * Exercise GIF media: © Gym visual — gymvisual.com (attribution required).
 */
import type { Exercise } from "./types";

export const OPENGYM_EXERCISES: Exercise[] = ${JSON.stringify(exercises, null, 2)};
`;

writeFileSync("src/data/openGymExercises.ts", ts);
console.log(`Written to src/data/openGymExercises.ts`);
