import { PRODUCT_CONFIG } from "@/lib/productConfig";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { WorkoutClient } from "./WorkoutClient";

export const metadata: Metadata = {
  title: "My Workout — AI-powered training plan",
  description:
    "Get a personalized weekly workout plan from the AI coach. Set your goals, experience, and equipment — then train.",
  alternates: { canonical: "/workout" },
};

export default function WorkoutPage() {
  if (!PRODUCT_CONFIG.features.userWorkspace || !PRODUCT_CONFIG.features.aiCoach) notFound();
  return (
    <div className="mx-auto max-w-5xl px-4 py-8 sm:px-6 sm:py-10 lg:px-8">
      <Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "My Workout" }]} />
      <div className="mb-8">
        <p className="easeur-rainbow inline-block text-xs font-bold uppercase tracking-[0.15em]">AI-powered</p>
        <h1 className="mt-1 text-3xl font-extrabold tracking-tight text-slate-900 sm:text-4xl">
          My Workout
        </h1>
        <p className="mt-2 max-w-2xl text-slate-600">
          Your personalized training plan, generated by AI based on your goals, experience, and equipment.
        </p>
      </div>
      <WorkoutClient />
    </div>
  );
}
