/**
 * GENERATED by scripts/import-repdb.mjs — do not edit by hand.
 * Curated subset of the free RepDB exercise dataset.
 * License: free for commercial in-app use WITH ATTRIBUTION (https://repdb.co).
 * These individual exercises are embedded in-app; the dataset is not
 * redistributed as a standalone bundle (per RepDB data license).
 */
import type { Exercise } from "./types";

export const GENERATED_EXERCISES: Exercise[] = [
  {
    "id": "pull-up",
    "name": "Pull-Up",
    "primaryMuscles": [
      "latissimus-dorsi"
    ],
    "secondaryMuscles": [
      "biceps-brachii",
      "posterior-deltoid",
      "rhomboids"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "Pull-up bar"
    ],
    "summary": "A bodyweight compound pull targeting the lats and biceps.",
    "keyCue": "Hang from a bar with an overhand grip, slightly wider than shoulder-width",
    "steps": [
      "Hang from a bar with an overhand grip, slightly wider than shoulder-width.",
      "Pull yourself up until your chin is over the bar.",
      "Lower yourself under control to a dead hang.",
      "Repeat."
    ],
    "tips": [
      "Avoid swinging or kipping.",
      "Engage your lats by pulling your elbows down."
    ],
    "contentSource": "repdb",
    "repdbImageId": "pull-up"
  },
  {
    "id": "wide-grip-seated-cable-row",
    "name": "Wide Grip Seated Cable Row",
    "primaryMuscles": [
      "latissimus-dorsi",
      "rhomboids"
    ],
    "secondaryMuscles": [
      "biceps-brachii",
      "posterior-deltoid"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "Cable"
    ],
    "summary": "A seated rowing variation with a wide grip emphasizing the upper back.",
    "keyCue": "Sit at a cable row station with feet on the platform",
    "steps": [
      "Sit at a cable row station with feet on the platform.",
      "Grip a wide bar with an overhand grip.",
      "Pull the bar toward your upper abdomen, squeezing your shoulder blades.",
      "Extend your arms back to the starting position with control.",
      "Repeat."
    ],
    "tips": [
      "Keep your torso upright and avoid rocking back and forth.",
      "Drive your elbows high and wide to target the upper back.",
      "Maintain a slight bend in your knees throughout the set."
    ],
    "contentSource": "repdb",
    "repdbImageId": "wide-grip-seated-cable-row"
  },
  {
    "id": "assisted-pull-ups",
    "name": "Assisted Pull Ups",
    "primaryMuscles": [
      "latissimus-dorsi"
    ],
    "secondaryMuscles": [
      "biceps-brachii",
      "forearm-flexors",
      "posterior-deltoid",
      "rhomboids"
    ],
    "difficulty": "beginner",
    "equipment": [
      "Assisted pull-up machine"
    ],
    "summary": "A machine-assisted pull-up reducing the effective body weight, allowing beginners to train the lats through a full range.",
    "keyCue": "Place your knees on the assisted pull-up machine pad",
    "steps": [
      "Place your knees on the assisted pull-up machine pad.",
      "Grip the bar with palms facing away, slightly wider than shoulders.",
      "Pull your chest toward the bar by driving your elbows down.",
      "Lower yourself under control to a full hang.",
      "Repeat for the desired number of reps."
    ],
    "tips": [
      "Pull your shoulder blades down before bending your arms.",
      "Avoid swinging or using momentum from the knee pad.",
      "Decrease the assistance over time to progress toward unassisted reps."
    ],
    "contentSource": "repdb",
    "repdbImageId": "assisted-pull-ups"
  },
  {
    "id": "band-assisted-pull-ups",
    "name": "Band Assisted Pull Ups",
    "primaryMuscles": [
      "latissimus-dorsi"
    ],
    "secondaryMuscles": [
      "biceps-brachii",
      "forearm-flexors",
      "posterior-deltoid",
      "rhomboids"
    ],
    "difficulty": "beginner",
    "equipment": [
      "Resistance band"
    ],
    "summary": "A pull-up variation using a resistance band for assistance, reducing the load to build toward unassisted reps.",
    "keyCue": "Loop a resistance band over the pull-up bar and step one foot into it",
    "steps": [
      "Loop a resistance band over the pull-up bar and step one foot into it.",
      "Grip the bar with palms facing away, shoulder-width apart.",
      "Pull your chest toward the bar by driving your elbows down.",
      "Lower yourself under control to a full hang.",
      "Repeat for the desired number of reps."
    ],
    "tips": [
      "Avoid letting the band's recoil bounce you out of the bottom.",
      "Keep the banded foot steady so the band cannot slip off.",
      "Progress to thinner bands as your pulling strength increases."
    ],
    "contentSource": "repdb",
    "repdbImageId": "band-assisted-pull-ups"
  },
  {
    "id": "barbell-pullover",
    "name": "Barbell Pullover",
    "primaryMuscles": [
      "latissimus-dorsi",
      "pectoralis-major-sternal"
    ],
    "secondaryMuscles": [
      "triceps-brachii"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "Barbell"
    ],
    "summary": "A compound movement stretching and loading the lats and chest through a wide arc.",
    "keyCue": "Lie across a bench with a barbell held over your chest",
    "steps": [
      "Lie across a bench with a barbell held over your chest.",
      "Lower the bar back over your head in an arc.",
      "Pull it back to the start over your chest.",
      "Repeat."
    ],
    "tips": [
      "Keep a slight bend in the elbows.",
      "Engage the lats to drive the bar back."
    ],
    "contentSource": "repdb",
    "repdbImageId": "barbell-pullover"
  },
  {
    "id": "bench-press",
    "name": "Barbell Bench Press",
    "primaryMuscles": [
      "pectoralis-major-sternal"
    ],
    "secondaryMuscles": [
      "anterior-deltoid",
      "triceps-brachii"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "Barbell"
    ],
    "summary": "A compound pushing movement that targets the chest, shoulders, and triceps.",
    "keyCue": "Lie flat on a bench with your eyes under the bar",
    "steps": [
      "Lie flat on a bench with your eyes under the bar.",
      "Grip the bar slightly wider than shoulder-width.",
      "Unrack the bar and lower it to your mid-chest.",
      "Press the bar back up to full arm extension.",
      "Repeat for the desired number of reps."
    ],
    "tips": [
      "Keep your feet flat on the floor.",
      "Maintain a slight arch in your lower back.",
      "Drive through your legs for stability."
    ],
    "contentSource": "repdb",
    "repdbImageId": "bench-press",
    "video": {
      "src": "/exercise-media/bench-press.mp4",
      "poster": "/exercise-media/bench-press.webp"
    }
  },
  {
    "id": "knee-push-ups",
    "name": "Knee Push Ups",
    "primaryMuscles": [
      "pectoralis-major-sternal"
    ],
    "secondaryMuscles": [
      "anterior-deltoid",
      "rectus-abdominis",
      "triceps-brachii"
    ],
    "difficulty": "beginner",
    "equipment": [
      "Bodyweight"
    ],
    "summary": "A beginner-friendly push-up variation performed from the knees, reducing bodyweight load while building chest and triceps strength.",
    "keyCue": "Start in a push-up position with your knees on the floor",
    "steps": [
      "Start in a push-up position with your knees on the floor.",
      "Place your hands shoulder-width apart on the ground.",
      "Keep your body in a straight line from knees to shoulders.",
      "Lower your chest toward the floor by bending your elbows.",
      "Press through your hands to return to the starting position.",
      "Repeat for the desired number of reps."
    ],
    "tips": [
      "Squeeze your glutes to keep your hips from sagging.",
      "Keep your elbows at roughly a 45-degree angle from your torso.",
      "Lower with control instead of dropping your chest quickly."
    ],
    "contentSource": "repdb",
    "repdbImageId": "knee-push-ups"
  },
  {
    "id": "push-up",
    "name": "Push-Up",
    "primaryMuscles": [
      "pectoralis-major-sternal",
      "triceps-brachii"
    ],
    "secondaryMuscles": [
      "anterior-deltoid"
    ],
    "difficulty": "beginner",
    "equipment": [
      "Bodyweight"
    ],
    "summary": "A fundamental bodyweight exercise for the chest, shoulders, and triceps.",
    "keyCue": "Start in a high plank position with hands shoulder-width apart",
    "steps": [
      "Start in a high plank position with hands shoulder-width apart.",
      "Lower your body until your chest nearly touches the floor.",
      "Push back up to the starting position.",
      "Keep your body in a straight line throughout.",
      "Repeat."
    ],
    "tips": [
      "Tuck your elbows toward your body rather than flaring them out wide.",
      "Brace your core and squeeze your glutes to prevent sagging hips.",
      "Keep your neck neutral by gazing slightly ahead of your hands."
    ],
    "contentSource": "repdb",
    "repdbImageId": "push-up"
  },
  {
    "id": "db-fly",
    "name": "Dumbbell Fly",
    "primaryMuscles": [
      "pectoralis-major-sternal"
    ],
    "secondaryMuscles": [
      "anterior-deltoid"
    ],
    "difficulty": "beginner",
    "equipment": [
      "Dumbbells"
    ],
    "summary": "An isolation exercise that stretches and contracts the pectorals through a wide arc of motion.",
    "keyCue": "Lie flat on a bench with dumbbells held above your chest, palms facing each other",
    "steps": [
      "Lie flat on a bench with dumbbells held above your chest, palms facing each other.",
      "With a slight bend in the elbows, lower the dumbbells out to the sides.",
      "Return to the start by squeezing your chest.",
      "Repeat."
    ],
    "tips": [
      "Keep a consistent bend in the elbows throughout.",
      "Do not let the dumbbells go too low."
    ],
    "contentSource": "repdb",
    "repdbImageId": "db-fly"
  },
  {
    "id": "machine-chest-fly",
    "name": "Machine Chest Fly",
    "primaryMuscles": [
      "pectoralis-major-sternal"
    ],
    "secondaryMuscles": [
      "anterior-deltoid"
    ],
    "difficulty": "beginner",
    "equipment": [
      "Fly machine"
    ],
    "summary": "A chest isolation exercise performed on a machine that arcs the handles together in front of the body.",
    "keyCue": "Sit in the chest fly machine and adjust the seat so the handles align with your chest",
    "steps": [
      "Sit in the chest fly machine and adjust the seat so the handles align with your chest.",
      "Grip the handles with a slight bend in your elbows.",
      "Bring the handles together in front of your chest in a smooth arc.",
      "Squeeze your pectorals at the point of peak contraction.",
      "Return under control to the starting position without slamming the weight.",
      "Repeat for the desired number of reps."
    ],
    "tips": [
      "Keep a slight, fixed bend in your elbows throughout.",
      "Focus on squeezing the chest rather than pushing with the arms.",
      "Control the return instead of letting the weight stack slam."
    ],
    "contentSource": "repdb",
    "repdbImageId": "machine-chest-fly",
    "video": {
      "src": "/exercise-media/machine-chest-fly.mp4",
      "poster": "/exercise-media/machine-chest-fly.webp"
    }
  },
  {
    "id": "dips",
    "name": "Chest Dips",
    "primaryMuscles": [
      "pectoralis-major-costal",
      "triceps-brachii"
    ],
    "secondaryMuscles": [
      "anterior-deltoid"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "Dip station"
    ],
    "summary": "A compound bodyweight exercise targeting the lower chest and triceps.",
    "keyCue": "Grip parallel dip bars and lift yourself to the top position with arms locked",
    "steps": [
      "Grip parallel dip bars and lift yourself to the top position with arms locked.",
      "Lean your torso forward slightly.",
      "Lower your body by bending your elbows until shoulders are below elbows.",
      "Press back up to the starting position.",
      "Repeat."
    ],
    "tips": [
      "Keep your shoulders pulled down away from your ears.",
      "Bend your knees and cross your ankles to minimize swinging.",
      "Stop the descent if you feel pinching in your shoulders."
    ],
    "contentSource": "repdb",
    "repdbImageId": "dips"
  },
  {
    "id": "assisted-dips",
    "name": "Machine Assisted Dips",
    "primaryMuscles": [
      "pectoralis-major-costal",
      "triceps-brachii"
    ],
    "secondaryMuscles": [
      "anterior-deltoid",
      "rhomboids"
    ],
    "difficulty": "beginner",
    "equipment": [
      "Dip machine"
    ],
    "summary": "A beginner-friendly dip performed on an assisted machine that offsets body weight, training the chest and triceps.",
    "keyCue": "Step onto the assisted dip machine with knees on the pad",
    "steps": [
      "Step onto the assisted dip machine with knees on the pad.",
      "Grip the parallel bars and support your weight with straight arms.",
      "Lower your body by bending your elbows until shoulders are below elbows.",
      "Press back up to the start position.",
      "Repeat for the desired number of reps."
    ],
    "tips": [
      "Keep your elbows tracking back rather than flaring out wide.",
      "Stop the descent if you feel pinching in the shoulders.",
      "Reduce the assistance gradually as pressing strength improves."
    ],
    "contentSource": "repdb",
    "repdbImageId": "assisted-dips"
  },
  {
    "id": "decline-bench-press-barbell",
    "name": "Decline Barbell Bench Press",
    "primaryMuscles": [
      "pectoralis-major-costal"
    ],
    "secondaryMuscles": [
      "anterior-deltoid",
      "triceps-brachii"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "Barbell"
    ],
    "summary": "A barbell compound press on a decline bench emphasizing the lower chest.",
    "keyCue": "Set the bench to a decline angle. Lie down and secure your feet",
    "steps": [
      "Set the bench to a decline angle. Lie down and secure your feet.",
      "Grip the bar slightly wider than shoulder-width.",
      "Lower the bar to your lower chest, then press back up.",
      "Repeat."
    ],
    "tips": [
      "Control the descent.",
      "Keep elbows at about 45 degrees to the torso."
    ],
    "contentSource": "repdb",
    "repdbImageId": "decline-bench-press-barbell",
    "externalMediaId": "Decline_Barbell_Bench_Press"
  },
  {
    "id": "decline-bench-press",
    "name": "Decline Bench Press",
    "primaryMuscles": [
      "pectoralis-major-costal"
    ],
    "secondaryMuscles": [
      "anterior-deltoid",
      "triceps-brachii"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "Dumbbells"
    ],
    "summary": "A compound chest press on a decline bench targeting the lower pectorals.",
    "keyCue": "Set the bench to a decline angle. Lie down and secure your feet",
    "steps": [
      "Set the bench to a decline angle. Lie down and secure your feet.",
      "Unrack the barbell and lower it to your lower chest.",
      "Press back up to the start.",
      "Repeat."
    ],
    "tips": [
      "Keep your back flat on the bench.",
      "Use a spotter when working with heavier loads."
    ],
    "contentSource": "repdb",
    "repdbImageId": "decline-bench-press"
  },
  {
    "id": "ring-dips",
    "name": "Ring Dips",
    "primaryMuscles": [
      "pectoralis-major-costal",
      "triceps-brachii"
    ],
    "secondaryMuscles": [
      "anterior-deltoid"
    ],
    "difficulty": "advanced",
    "equipment": [
      "rings"
    ],
    "summary": "A challenging bodyweight dip performed on gymnastic rings, demanding greater stabilization than bar dips.",
    "keyCue": "Support yourself on the rings with arms locked out",
    "steps": [
      "Support yourself on the rings with arms locked out.",
      "Lower your body by bending the elbows until upper arms are parallel to the ground.",
      "Press back up to the starting position.",
      "Repeat."
    ],
    "tips": [
      "Keep the rings close to your body.",
      "Turn the rings out at the top for additional chest activation."
    ],
    "contentSource": "repdb",
    "repdbImageId": "ring-dips",
    "externalMediaId": "Ring_Dips"
  },
  {
    "id": "bodyweight-overhead-press",
    "name": "Bodyweight Overhead Press",
    "primaryMuscles": [
      "anterior-deltoid",
      "triceps-brachii"
    ],
    "secondaryMuscles": [
      "trapezius"
    ],
    "difficulty": "beginner",
    "equipment": [
      "Bodyweight"
    ],
    "summary": "A bodyweight press performed in a pike position facing a wall, replicating the overhead pressing pattern with the shoulders and triceps.",
    "keyCue": "Stand facing a wall in a pike position with hands on the ground",
    "steps": [
      "Stand facing a wall in a pike position with hands on the ground.",
      "Walk your feet closer for a more vertical body line.",
      "Lower your head toward the floor by bending your elbows.",
      "Press through your hands to extend your arms.",
      "Repeat for the desired number of reps."
    ],
    "tips": [
      "Keep your hips high so the load stays over your shoulders.",
      "Avoid flaring your elbows straight out to the sides.",
      "Spread your fingers and grip the floor for stability."
    ],
    "contentSource": "repdb",
    "repdbImageId": "bodyweight-overhead-press"
  },
  {
    "id": "tricep-pushdown",
    "name": "Cable Tricep Pushdown",
    "primaryMuscles": [
      "triceps-brachii"
    ],
    "secondaryMuscles": [],
    "difficulty": "beginner",
    "equipment": [
      "Cable"
    ],
    "summary": "An isolation exercise targeting the triceps using a cable machine.",
    "keyCue": "Stand facing a cable machine with a straight bar attachment",
    "steps": [
      "Stand facing a cable machine with a straight bar attachment.",
      "Grip the bar and pin your elbows to your sides.",
      "Push the bar down until your arms are fully extended.",
      "Slowly return to the starting position.",
      "Repeat."
    ],
    "tips": [
      "Keep your torso upright.",
      "Only your forearms should move."
    ],
    "contentSource": "repdb",
    "repdbImageId": "tricep-pushdown",
    "video": {
      "src": "/exercise-media/tricep-pushdown.mp4",
      "poster": "/exercise-media/tricep-pushdown.webp"
    }
  },
  {
    "id": "bench-dips",
    "name": "Bench Dips",
    "primaryMuscles": [
      "triceps-brachii"
    ],
    "secondaryMuscles": [
      "anterior-deltoid",
      "pectoralis-major-costal"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "Bodyweight"
    ],
    "summary": "A bodyweight pressing movement with hands on a bench behind the body, emphasizing the triceps.",
    "keyCue": "Sit on a bench and place your hands on the edge beside your hips",
    "steps": [
      "Sit on a bench and place your hands on the edge beside your hips.",
      "Slide your hips off the bench with legs extended.",
      "Lower your body by bending your elbows to 90 degrees.",
      "Press through your palms to return to the start.",
      "Repeat for the desired number of reps."
    ],
    "tips": [
      "Keep your hips close to the bench as you lower.",
      "Avoid letting your shoulders roll forward at the bottom.",
      "Bend your knees to make the movement easier."
    ],
    "contentSource": "repdb",
    "repdbImageId": "bench-dips",
    "externalMediaId": "Bench_Dips"
  },
  {
    "id": "deadlift",
    "name": "Barbell Deadlift",
    "primaryMuscles": [
      "erector-spinae",
      "gluteus-maximus",
      "hamstrings"
    ],
    "secondaryMuscles": [
      "quadriceps",
      "trapezius"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "Barbell"
    ],
    "summary": "A full-body compound lift that primarily targets the posterior chain.",
    "keyCue": "Stand with feet hip-width apart, bar over mid-foot",
    "steps": [
      "Stand with feet hip-width apart, bar over mid-foot.",
      "Hinge at the hips and grip the bar.",
      "Brace your core and lift by extending hips and knees.",
      "Stand tall at the top, then lower under control.",
      "Repeat."
    ],
    "tips": [
      "Keep the bar close to your body.",
      "Do not round your lower back."
    ],
    "contentSource": "repdb",
    "repdbImageId": "deadlift",
    "externalMediaId": "Barbell_Deadlift",
    "video": {
      "src": "/exercise-media/deadlift.mp4",
      "poster": "/exercise-media/deadlift.webp"
    }
  },
  {
    "id": "good-morning",
    "name": "Good Morning",
    "primaryMuscles": [
      "erector-spinae",
      "gluteus-maximus",
      "hamstrings"
    ],
    "secondaryMuscles": [],
    "difficulty": "intermediate",
    "equipment": [
      "Barbell"
    ],
    "summary": "A hip-hinge movement with a barbell on the back for posterior chain development.",
    "keyCue": "Stand with a barbell across your upper back",
    "steps": [
      "Stand with a barbell across your upper back.",
      "Hinge at the hips, pushing them back while keeping your back flat.",
      "Lower your torso until it's nearly parallel to the floor.",
      "Drive your hips forward to return to standing.",
      "Repeat."
    ],
    "tips": [
      "Start with a light bar and master the hinge first.",
      "Keep a soft bend in your knees throughout.",
      "Stop the descent if your lower back starts to round."
    ],
    "contentSource": "repdb",
    "repdbImageId": "good-morning",
    "externalMediaId": "Good_Morning"
  },
  {
    "id": "back-extension",
    "name": "Back Extension",
    "primaryMuscles": [
      "erector-spinae"
    ],
    "secondaryMuscles": [
      "gluteus-maximus",
      "hamstrings"
    ],
    "difficulty": "beginner",
    "equipment": [
      "Bodyweight"
    ],
    "summary": "An isolation movement targeting the lower back erector spinae on a hyperextension bench.",
    "keyCue": "Lie face down on a hyperextension bench with hips at the pad edge",
    "steps": [
      "Lie face down on a hyperextension bench with hips at the pad edge.",
      "Lower your upper body toward the floor.",
      "Raise your torso back up until your body is straight.",
      "Repeat."
    ],
    "tips": [
      "Keep movements controlled.",
      "Do not hyperextend beyond neutral spine."
    ],
    "contentSource": "repdb",
    "repdbImageId": "back-extension"
  },
  {
    "id": "bodyweight-good-morning",
    "name": "Bodyweight Good Morning",
    "primaryMuscles": [
      "erector-spinae",
      "hamstrings"
    ],
    "secondaryMuscles": [
      "gluteus-maximus"
    ],
    "difficulty": "beginner",
    "equipment": [
      "Bodyweight"
    ],
    "summary": "A bodyweight hip hinge with hands behind the head, strengthening the hamstrings and spinal erectors.",
    "keyCue": "Stand with feet hip-width apart and hands behind your head",
    "steps": [
      "Stand with feet hip-width apart and hands behind your head.",
      "Keep a slight bend in your knees and brace your core.",
      "Hinge at the hips and lower your torso toward parallel.",
      "Drive your hips forward to return to standing.",
      "Repeat for the desired number of reps."
    ],
    "tips": [
      "Push your hips back as if closing a door behind you.",
      "Keep your spine neutral from head to tailbone throughout.",
      "Stop the descent when your hamstrings reach their stretch limit."
    ],
    "contentSource": "repdb",
    "repdbImageId": "bodyweight-good-morning"
  },
  {
    "id": "bird-dog-hold",
    "name": "Bird Dog Hold",
    "primaryMuscles": [
      "erector-spinae",
      "rectus-abdominis"
    ],
    "secondaryMuscles": [
      "gluteus-maximus",
      "obliques",
      "posterior-deltoid"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "Bodyweight"
    ],
    "summary": "A static core hold balancing on all fours with one arm and the opposite leg extended, training spinal stability.",
    "keyCue": "Start on all fours with hands under shoulders and knees under hips",
    "steps": [
      "Start on all fours with hands under shoulders and knees under hips.",
      "Extend one arm forward and the opposite leg back.",
      "Keep your core tight and body level.",
      "Hold the position without rotating your torso.",
      "Hold for time. Complete on one side, then switch."
    ],
    "tips": [
      "Reach long through your fingertips and heel in opposite directions.",
      "Push the floor away with your supporting hand to stay stable.",
      "Breathe steadily instead of holding your breath."
    ],
    "contentSource": "repdb",
    "repdbImageId": "bird-dog-hold"
  },
  {
    "id": "bodyweight-calf-raise",
    "name": "Bodyweight Calf Raise",
    "primaryMuscles": [
      "gastrocnemius"
    ],
    "secondaryMuscles": [
      "soleus"
    ],
    "difficulty": "beginner",
    "equipment": [
      "Bodyweight"
    ],
    "summary": "A beginner-friendly calf raise using body weight only on flat ground, strengthening the gastrocnemius and soleus.",
    "keyCue": "Stand with feet hip-width apart on a flat surface",
    "steps": [
      "Stand with feet hip-width apart on a flat surface.",
      "Push up onto the balls of your feet as high as possible.",
      "Squeeze your calves at the top.",
      "Lower your heels back to the floor under control.",
      "Repeat for the desired number of reps."
    ],
    "tips": [
      "Use light fingertip support for balance if needed.",
      "Control the lowering phase instead of dropping your heels quickly.",
      "Keep your ankles from rolling outward as you rise."
    ],
    "contentSource": "repdb",
    "repdbImageId": "bodyweight-calf-raise"
  },
  {
    "id": "machine-calf-raise",
    "name": "Machine Calf Raise",
    "primaryMuscles": [
      "gastrocnemius",
      "soleus"
    ],
    "secondaryMuscles": [],
    "difficulty": "beginner",
    "equipment": [
      "Calf raise machine"
    ],
    "summary": "A standing machine exercise isolating the calves through a full stretch and rise onto the toes.",
    "keyCue": "Stand in the calf raise machine with the balls of your feet on the platform",
    "steps": [
      "Stand in the calf raise machine with the balls of your feet on the platform.",
      "Position the shoulder pads firmly.",
      "Lower your heels below the platform for a full stretch.",
      "Push through the balls of your feet to rise onto your toes.",
      "Squeeze your calves at the top.",
      "Lower with control and repeat."
    ],
    "tips": [
      "Keep your knees straight but not locked throughout the movement.",
      "Pause briefly in the stretched position instead of bouncing.",
      "Avoid cutting the range of motion short as fatigue sets in."
    ],
    "contentSource": "repdb",
    "repdbImageId": "machine-calf-raise"
  },
  {
    "id": "barbell-calf-raise",
    "name": "Barbell Calf Raise",
    "primaryMuscles": [
      "gastrocnemius"
    ],
    "secondaryMuscles": [
      "soleus"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "Barbell"
    ],
    "summary": "A standing calf raise loaded with a barbell across the upper back, using a raised platform for a deeper heel stretch.",
    "keyCue": "Place a barbell across your upper back as in a squat",
    "steps": [
      "Place a barbell across your upper back as in a squat.",
      "Stand with the balls of your feet on a raised platform.",
      "Push up onto your toes as high as possible.",
      "Pause and squeeze your calves at the top.",
      "Lower your heels below the platform and repeat."
    ],
    "tips": [
      "Avoid bouncing out of the bottom stretch position.",
      "Keep your knees straight but not locked throughout the set.",
      "Move slowly to stay balanced under the bar."
    ],
    "contentSource": "repdb",
    "repdbImageId": "barbell-calf-raise"
  },
  {
    "id": "donkey-calf-raise",
    "name": "Donkey Calf Raise",
    "primaryMuscles": [
      "gastrocnemius"
    ],
    "secondaryMuscles": [
      "soleus"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "Bodyweight"
    ],
    "summary": "A bent-over calf raise that maximizes calf stretch by hinging at the hips.",
    "keyCue": "Bend at the hips and rest the forearms on a bench or sturdy support",
    "steps": [
      "Bend at the hips and rest the forearms on a bench or sturdy support.",
      "Place the balls of the feet on a raised platform with heels free.",
      "Drop the heels below platform level for a full stretch.",
      "Drive up onto the toes as high as possible, squeezing the calves.",
      "Lower under control to a deep stretch."
    ],
    "tips": [
      "Pause briefly at the top to maximize the contraction.",
      "Use a slow eccentric for full stretch.",
      "Add a partner or weight on the lower back for resistance."
    ],
    "contentSource": "repdb",
    "repdbImageId": "donkey-calf-raise"
  },
  {
    "id": "dumbbell-calf-raise",
    "name": "Dumbbell Calf Raise",
    "primaryMuscles": [
      "gastrocnemius",
      "soleus"
    ],
    "secondaryMuscles": [
      "forearm-flexors"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "Dumbbells"
    ],
    "summary": "A weighted calf raise holding dumbbells at the sides, performed on an elevated edge for a full stretch.",
    "keyCue": "Stand holding a dumbbell in each hand at your sides",
    "steps": [
      "Stand holding a dumbbell in each hand at your sides.",
      "Place the balls of your feet on a raised surface with heels hanging off.",
      "Press through the balls of your feet to raise your heels as high as possible.",
      "Squeeze your calves at the top of the movement.",
      "Lower your heels below the platform to stretch the calves.",
      "Repeat for the desired number of reps."
    ],
    "tips": [
      "Avoid bouncing out of the bottom stretch position.",
      "Keep your legs straight but not locked throughout.",
      "Prevent your ankles from rolling outward as you rise."
    ],
    "contentSource": "repdb",
    "repdbImageId": "dumbbell-calf-raise"
  },
  {
    "id": "barbell-curl",
    "name": "Barbell Curl",
    "primaryMuscles": [
      "biceps-brachii"
    ],
    "secondaryMuscles": [
      "brachialis",
      "forearm-flexors"
    ],
    "difficulty": "beginner",
    "equipment": [
      "Barbell"
    ],
    "summary": "A classic biceps isolation exercise using a barbell for maximal loading.",
    "keyCue": "Stand holding a barbell with a shoulder-width underhand grip",
    "steps": [
      "Stand holding a barbell with a shoulder-width underhand grip.",
      "Curl the bar up toward your shoulders.",
      "Squeeze at the top, then lower under control.",
      "Repeat."
    ],
    "tips": [
      "Avoid swinging the torso.",
      "Keep elbows pinned at your sides."
    ],
    "contentSource": "repdb",
    "repdbImageId": "barbell-curl",
    "externalMediaId": "Barbell_Curl"
  },
  {
    "id": "bicep-curl",
    "name": "Dumbbell Bicep Curl",
    "primaryMuscles": [
      "biceps-brachii"
    ],
    "secondaryMuscles": [
      "brachialis",
      "forearm-flexors"
    ],
    "difficulty": "beginner",
    "equipment": [
      "Dumbbells"
    ],
    "summary": "An isolation exercise targeting the biceps.",
    "keyCue": "Stand holding dumbbells at your sides, palms forward",
    "steps": [
      "Stand holding dumbbells at your sides, palms forward.",
      "Curl the weights up toward your shoulders.",
      "Squeeze at the top, then lower under control.",
      "Repeat."
    ],
    "tips": [
      "Keep your elbows pinned to your sides.",
      "Avoid swinging the weights."
    ],
    "contentSource": "repdb",
    "repdbImageId": "bicep-curl",
    "externalMediaId": "Dumbbell_Bicep_Curl"
  },
  {
    "id": "cable-curl",
    "name": "Cable Curl",
    "primaryMuscles": [
      "biceps-brachii"
    ],
    "secondaryMuscles": [
      "brachialis"
    ],
    "difficulty": "beginner",
    "equipment": [
      "Cable"
    ],
    "summary": "A bicep curl using cable resistance for constant tension.",
    "keyCue": "Stand facing a low cable pulley with a straight bar or EZ-bar attachment",
    "steps": [
      "Stand facing a low cable pulley with a straight bar or EZ-bar attachment.",
      "Grip the bar with an underhand grip, elbows at your sides.",
      "Curl the bar up toward your shoulders.",
      "Lower with control.",
      "Repeat."
    ],
    "tips": [
      "Keep your elbows from drifting forward as you curl.",
      "Straighten your arms fully at the bottom of each rep.",
      "Avoid leaning back to help lift the weight."
    ],
    "contentSource": "repdb",
    "repdbImageId": "cable-curl"
  },
  {
    "id": "concentration-curl",
    "name": "Concentration Curl",
    "primaryMuscles": [
      "biceps-brachii"
    ],
    "secondaryMuscles": [
      "brachialis"
    ],
    "difficulty": "beginner",
    "equipment": [
      "Dumbbells"
    ],
    "summary": "An isolation curl performed seated for peak bicep contraction.",
    "keyCue": "Sit on a bench with legs spread, holding a dumbbell in one hand",
    "steps": [
      "Sit on a bench with legs spread, holding a dumbbell in one hand.",
      "Brace your elbow against the inside of your thigh.",
      "Curl the dumbbell up toward your shoulder.",
      "Lower with control.",
      "Repeat on both sides."
    ],
    "tips": [
      "Keep your upper arm vertical and let only the forearm move.",
      "Avoid swinging your torso to help the weight up.",
      "Match the reps on each arm to avoid muscle imbalances."
    ],
    "contentSource": "repdb",
    "repdbImageId": "concentration-curl"
  },
  {
    "id": "cable-hammer-curl",
    "name": "Cable Hammer Curl",
    "primaryMuscles": [
      "biceps-brachii",
      "brachialis",
      "brachioradialis"
    ],
    "secondaryMuscles": [
      "forearm-flexors"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "Cable"
    ],
    "summary": "A cable curl using a rope attachment with a neutral grip to target the brachialis and brachioradialis with constant tension.",
    "keyCue": "Attach a rope to a low cable pulley and stand facing the machine",
    "steps": [
      "Attach a rope to a low cable pulley and stand facing the machine.",
      "Grip the rope with a neutral (hammer) grip, palms facing each other.",
      "Curl the rope upward toward your shoulders, keeping elbows pinned at your sides.",
      "Squeeze at the top, then lower slowly to full extension.",
      "Repeat for the desired reps."
    ],
    "tips": [
      "Keep your elbows stationary throughout the movement.",
      "Pull the rope ends apart slightly at the top to increase contraction.",
      "Avoid swinging the torso."
    ],
    "contentSource": "repdb",
    "repdbImageId": "cable-hammer-curl"
  },
  {
    "id": "machine-shoulder-press",
    "name": "Machine Shoulder Press",
    "primaryMuscles": [
      "anterior-deltoid",
      "lateral-deltoid"
    ],
    "secondaryMuscles": [
      "trapezius",
      "triceps-brachii"
    ],
    "difficulty": "beginner",
    "equipment": [
      "Shoulder press machine"
    ],
    "summary": "A machine-based overhead pressing movement for the shoulders.",
    "keyCue": "Sit in the machine with your back against the pad",
    "steps": [
      "Sit in the machine with your back against the pad.",
      "Grip the handles at shoulder level.",
      "Press the handles overhead until arms are fully extended.",
      "Lower with control to the starting position.",
      "Repeat."
    ],
    "tips": [
      "Keep your lower back pressed into the pad without overarching.",
      "Keep your wrists stacked directly over your elbows as you press."
    ],
    "contentSource": "repdb",
    "repdbImageId": "machine-shoulder-press"
  },
  {
    "id": "barbell-front-raise",
    "name": "Barbell Front Raise",
    "primaryMuscles": [
      "anterior-deltoid"
    ],
    "secondaryMuscles": [
      "lateral-deltoid",
      "pectoralis-major-sternal"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "Barbell"
    ],
    "summary": "An isolation exercise raising a barbell from the thighs to shoulder height, targeting the front deltoids.",
    "keyCue": "Stand holding a barbell with an overhand grip at thigh level",
    "steps": [
      "Stand holding a barbell with an overhand grip at thigh level.",
      "Keep your arms straight and core braced.",
      "Raise the barbell in front of you to shoulder height.",
      "Pause briefly at the top.",
      "Lower under control and repeat."
    ],
    "tips": [
      "Use a light weight to avoid swinging the bar up.",
      "Avoid leaning back as the bar rises.",
      "Keep your wrists neutral rather than letting them bend backward."
    ],
    "contentSource": "repdb",
    "repdbImageId": "barbell-front-raise"
  },
  {
    "id": "ohp",
    "name": "Barbell Overhead Press",
    "primaryMuscles": [
      "anterior-deltoid",
      "lateral-deltoid"
    ],
    "secondaryMuscles": [
      "trapezius",
      "triceps-brachii"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "Barbell"
    ],
    "summary": "A compound overhead pressing movement targeting the shoulders and triceps.",
    "keyCue": "Stand with feet shoulder-width apart, bar at collarbone level",
    "steps": [
      "Stand with feet shoulder-width apart, bar at collarbone level.",
      "Brace your core and press the bar overhead.",
      "Lock out at the top with the bar over your mid-foot.",
      "Lower the bar back to collarbone height.",
      "Repeat."
    ],
    "tips": [
      "Do not lean back excessively.",
      "Squeeze your glutes for stability."
    ],
    "contentSource": "repdb",
    "repdbImageId": "ohp"
  },
  {
    "id": "handstand-push-ups",
    "name": "Handstand Push Ups",
    "primaryMuscles": [
      "anterior-deltoid",
      "triceps-brachii"
    ],
    "secondaryMuscles": [
      "lateral-deltoid",
      "rectus-abdominis",
      "trapezius"
    ],
    "difficulty": "advanced",
    "equipment": [
      "Bodyweight"
    ],
    "summary": "An inverted press against a wall, lowering the head to the floor and pressing back up to a full handstand.",
    "keyCue": "Kick up into a handstand against a wall with hands shoulder-width apart",
    "steps": [
      "Kick up into a handstand against a wall with hands shoulder-width apart.",
      "Brace your core and keep your body straight.",
      "Lower your head toward the floor by bending your elbows.",
      "Stop just before your head touches the ground.",
      "Press through your hands to return to full handstand.",
      "Repeat for the desired number of reps."
    ],
    "tips": [
      "Keep your elbows at roughly 45 degrees rather than flared wide.",
      "Brace your core so your back does not arch away from the wall.",
      "Build up through pike push-ups and partial ranges first."
    ],
    "contentSource": "repdb",
    "repdbImageId": "handstand-push-ups",
    "externalMediaId": "Handstand_Push-Ups"
  },
  {
    "id": "squat",
    "name": "Barbell Back Squat",
    "primaryMuscles": [
      "gluteus-maximus",
      "quadriceps"
    ],
    "secondaryMuscles": [
      "erector-spinae",
      "hamstrings"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "Barbell"
    ],
    "summary": "A compound lower-body movement targeting the quadriceps, glutes, and hamstrings.",
    "keyCue": "Position the bar on your upper traps",
    "steps": [
      "Position the bar on your upper traps.",
      "Unrack and step back, feet shoulder-width apart.",
      "Brace your core and squat down until thighs are parallel.",
      "Drive through your heels to stand back up.",
      "Repeat."
    ],
    "tips": [
      "Keep your chest up throughout the movement.",
      "Push your knees out in line with your toes."
    ],
    "contentSource": "repdb",
    "repdbImageId": "squat",
    "video": {
      "src": "/exercise-media/squat.mp4",
      "poster": "/exercise-media/squat.webp"
    }
  },
  {
    "id": "hip-thrust",
    "name": "Barbell Hip Thrust",
    "primaryMuscles": [
      "gluteus-maximus",
      "gluteus-medius"
    ],
    "secondaryMuscles": [
      "hamstrings"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "Barbell"
    ],
    "summary": "A compound glute exercise using a barbell across the hips.",
    "keyCue": "Sit on the floor with your upper back against a bench, barbell across your hips",
    "steps": [
      "Sit on the floor with your upper back against a bench, barbell across your hips.",
      "Drive your hips up until your thighs are parallel to the floor.",
      "Squeeze your glutes at the top.",
      "Lower your hips back down with control.",
      "Repeat."
    ],
    "tips": [
      "Tuck your chin and keep your ribs down at the top.",
      "Finish with your shins vertical, driving through your heels.",
      "Reach full hip extension without arching your lower back."
    ],
    "contentSource": "repdb",
    "repdbImageId": "hip-thrust",
    "externalMediaId": "Barbell_Hip_Thrust"
  },
  {
    "id": "bulgarian-split-squat",
    "name": "Bulgarian Split Squat",
    "primaryMuscles": [
      "gluteus-maximus",
      "quadriceps"
    ],
    "secondaryMuscles": [
      "hamstrings"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "Dumbbells"
    ],
    "summary": "A single-leg squat variation with the rear foot elevated.",
    "keyCue": "Stand in front of a bench, place one foot behind you on the bench",
    "steps": [
      "Stand in front of a bench, place one foot behind you on the bench.",
      "Hold dumbbells at your sides.",
      "Lower your body until your front thigh is parallel to the floor.",
      "Push through your front heel to stand back up.",
      "Repeat on both sides."
    ],
    "tips": [
      "Keep most of your weight on the front leg.",
      "Track your front knee over your toes without letting it cave inward.",
      "Square your hips forward and avoid rotating toward the bench."
    ],
    "contentSource": "repdb",
    "repdbImageId": "bulgarian-split-squat"
  },
  {
    "id": "hack-squat",
    "name": "Hack Squat",
    "primaryMuscles": [
      "gluteus-maximus",
      "quadriceps"
    ],
    "secondaryMuscles": [
      "gastrocnemius",
      "hamstrings"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "Hack squat"
    ],
    "summary": "A compound lower-body machine exercise on the hack squat sled, targeting the quadriceps through a guided squat pattern.",
    "keyCue": "Load the hack squat machine and step on, positioning your back and shoulders against the pads",
    "steps": [
      "Load the hack squat machine and step on, positioning your back and shoulders against the pads.",
      "Place your feet shoulder-width on the platform with toes turned out slightly.",
      "Unlock the safety handles and lower the sled by bending at the knees and hips.",
      "Descend until your thighs are at least parallel to the platform.",
      "Drive through your heels to extend the legs and push the sled back to the start.",
      "Re-engage the safety handles after your final rep."
    ],
    "tips": [
      "Keep your lower back pressed against the pad throughout the movement.",
      "Placing the feet higher on the platform shifts emphasis to the glutes and hamstrings.",
      "Control the descent; do not bounce out of the bottom position."
    ],
    "contentSource": "repdb",
    "repdbImageId": "hack-squat",
    "externalMediaId": "Hack_Squat",
    "video": {
      "src": "/exercise-media/hack-squat.mp4",
      "poster": "/exercise-media/hack-squat.webp"
    }
  },
  {
    "id": "leg-extension",
    "name": "Leg Extension",
    "primaryMuscles": [
      "quadriceps"
    ],
    "secondaryMuscles": [],
    "difficulty": "beginner",
    "equipment": [
      "Leg extension machine"
    ],
    "summary": "An isolation exercise for the quadriceps using a machine.",
    "keyCue": "Sit in the leg extension machine with ankles behind the pad",
    "steps": [
      "Sit in the leg extension machine with ankles behind the pad.",
      "Extend your legs until they are straight.",
      "Squeeze your quads at the top.",
      "Lower with control.",
      "Repeat."
    ],
    "tips": [
      "Adjust the seat so your knees align with the machine's pivot point.",
      "Keep your back pressed against the pad throughout.",
      "Avoid swinging the weight up with momentum."
    ],
    "contentSource": "repdb",
    "repdbImageId": "leg-extension",
    "video": {
      "src": "/exercise-media/leg-extension.mp4",
      "poster": "/exercise-media/leg-extension.webp"
    }
  },
  {
    "id": "leg-press",
    "name": "Leg Press",
    "primaryMuscles": [
      "gluteus-maximus",
      "quadriceps"
    ],
    "secondaryMuscles": [
      "hamstrings"
    ],
    "difficulty": "beginner",
    "equipment": [
      "Leg press"
    ],
    "summary": "A machine-based compound movement for the quads and glutes.",
    "keyCue": "Sit in the leg press machine with feet shoulder-width apart on the platform",
    "steps": [
      "Sit in the leg press machine with feet shoulder-width apart on the platform.",
      "Release the safety catches and lower the platform by bending your knees.",
      "Push the platform back up until legs are nearly straight.",
      "Do not lock your knees at the top.",
      "Repeat."
    ],
    "tips": [
      "Keep your lower back and hips pressed into the seat.",
      "Lower only as far as you can without your hips tucking under.",
      "Drive evenly through your whole foot, not just your toes."
    ],
    "contentSource": "repdb",
    "repdbImageId": "leg-press",
    "externalMediaId": "Leg_Press"
  },
  {
    "id": "rear-delt-fly",
    "name": "Rear Delt Fly",
    "primaryMuscles": [
      "posterior-deltoid",
      "rhomboids"
    ],
    "secondaryMuscles": [
      "trapezius"
    ],
    "difficulty": "beginner",
    "equipment": [
      "Dumbbells"
    ],
    "summary": "An isolation movement targeting the posterior deltoids and upper back.",
    "keyCue": "Hold dumbbells and hinge forward at the hips",
    "steps": [
      "Hold dumbbells and hinge forward at the hips.",
      "With a slight bend in elbows, raise the dumbbells out to the sides.",
      "Squeeze your shoulder blades at the top.",
      "Lower with control.",
      "Repeat."
    ],
    "tips": [
      "Choose a light weight to keep the movement strict.",
      "Avoid using momentum from the torso to swing the weights up.",
      "Lead with your elbows rather than your hands."
    ],
    "contentSource": "repdb",
    "repdbImageId": "rear-delt-fly"
  },
  {
    "id": "bench-pull",
    "name": "Bench Pull",
    "primaryMuscles": [
      "latissimus-dorsi",
      "rhomboids"
    ],
    "secondaryMuscles": [
      "biceps-brachii",
      "posterior-deltoid",
      "trapezius"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "Barbell"
    ],
    "summary": "A rowing exercise performed lying face down on an elevated bench, eliminating body momentum to target the lats and rhomboids.",
    "keyCue": "Lie face down on an elevated bench with arms hanging straight down",
    "steps": [
      "Lie face down on an elevated bench with arms hanging straight down.",
      "Grip a barbell or dumbbells below you.",
      "Row the weight up to the underside of the bench.",
      "Squeeze your shoulder blades at the top.",
      "Lower under control and repeat."
    ],
    "tips": [
      "Keep your chest glued to the bench to prevent cheating.",
      "Reach a full stretch at the bottom before each pull.",
      "Drive your elbows up and back rather than curling the weight."
    ],
    "contentSource": "repdb",
    "repdbImageId": "bench-pull"
  },
  {
    "id": "barbell-row",
    "name": "Bent-Over Barbell Row",
    "primaryMuscles": [
      "latissimus-dorsi",
      "rhomboids"
    ],
    "secondaryMuscles": [
      "biceps-brachii",
      "posterior-deltoid"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "Barbell"
    ],
    "summary": "A compound pulling movement that targets the upper and middle back.",
    "keyCue": "Hinge at the hips with a slight knee bend",
    "steps": [
      "Hinge at the hips with a slight knee bend.",
      "Grip the bar slightly wider than shoulder-width.",
      "Pull the bar to your lower chest, squeezing your shoulder blades.",
      "Lower the bar under control.",
      "Repeat."
    ],
    "tips": [
      "Keep your torso at roughly 45 degrees.",
      "Do not use momentum to swing the weight."
    ],
    "contentSource": "repdb",
    "repdbImageId": "barbell-row",
    "externalMediaId": "Bent_Over_Barbell_Row"
  },
  {
    "id": "bent-over-ez-bar-row",
    "name": "Bent-Over EZ-Bar Row",
    "primaryMuscles": [
      "latissimus-dorsi",
      "rhomboids"
    ],
    "secondaryMuscles": [
      "biceps-brachii",
      "posterior-deltoid"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "EZ bar"
    ],
    "summary": "A horizontal pulling movement with an EZ-bar for a wrist-friendly back rowing exercise.",
    "keyCue": "Hold an EZ-bar with an overhand grip, hinge at the hips to 45 degrees",
    "steps": [
      "Hold an EZ-bar with an overhand grip, hinge at the hips to 45 degrees.",
      "Pull the bar to your lower ribcage.",
      "Lower under control.",
      "Repeat."
    ],
    "tips": [
      "Keep your back flat throughout.",
      "Initiate with the elbows, not the hands."
    ],
    "contentSource": "repdb",
    "repdbImageId": "bent-over-ez-bar-row"
  },
  {
    "id": "shrug",
    "name": "Barbell Shrug",
    "primaryMuscles": [
      "trapezius"
    ],
    "secondaryMuscles": [
      "rhomboids"
    ],
    "difficulty": "beginner",
    "equipment": [
      "Barbell"
    ],
    "summary": "An isolation movement for the upper trapezius.",
    "keyCue": "Stand holding a barbell at arm's length with an overhand grip",
    "steps": [
      "Stand holding a barbell at arm's length with an overhand grip.",
      "Shrug your shoulders straight up toward your ears.",
      "Hold briefly at the top.",
      "Lower your shoulders back down with control.",
      "Repeat."
    ],
    "tips": [
      "Avoid rolling the shoulders forward or backward at the top.",
      "Keep your arms relaxed and let the traps do the work.",
      "Keep your neck neutral instead of jutting the chin forward."
    ],
    "contentSource": "repdb",
    "repdbImageId": "shrug",
    "externalMediaId": "Barbell_Shrug"
  },
  {
    "id": "db-shrug",
    "name": "Dumbbell Shrug",
    "primaryMuscles": [
      "trapezius"
    ],
    "secondaryMuscles": [
      "rhomboids"
    ],
    "difficulty": "beginner",
    "equipment": [
      "Dumbbells"
    ],
    "summary": "A dumbbell shrug targeting the upper trapezius for neck and upper back thickness.",
    "keyCue": "Stand holding dumbbells at your sides",
    "steps": [
      "Stand holding dumbbells at your sides.",
      "Shrug your shoulders straight up as high as possible.",
      "Hold briefly, then lower.",
      "Repeat."
    ],
    "tips": [
      "Do not roll your shoulders.",
      "Focus on squeezing the traps at the top."
    ],
    "contentSource": "repdb",
    "repdbImageId": "db-shrug",
    "externalMediaId": "Dumbbell_Shrug"
  },
  {
    "id": "upright-row",
    "name": "Barbell Upright Row",
    "primaryMuscles": [
      "lateral-deltoid",
      "trapezius"
    ],
    "secondaryMuscles": [
      "anterior-deltoid",
      "biceps-brachii"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "Barbell"
    ],
    "summary": "A compound pulling movement for the lateral deltoids and upper traps.",
    "keyCue": "Stand holding a barbell with a shoulder-width overhand grip",
    "steps": [
      "Stand holding a barbell with a shoulder-width overhand grip.",
      "Pull the bar straight up along your body toward your chin.",
      "Lead with your elbows, keeping them above your hands.",
      "Lower the bar with control.",
      "Repeat."
    ],
    "tips": [
      "Use a lighter weight if you feel pinching in your shoulders.",
      "Avoid bending your wrists excessively as the bar rises.",
      "Avoid swinging or using your legs to heave the weight up."
    ],
    "contentSource": "repdb",
    "repdbImageId": "upright-row"
  },
  {
    "id": "behind-the-back-barbell-shrug",
    "name": "Behind the Back Barbell Shrug",
    "primaryMuscles": [
      "trapezius"
    ],
    "secondaryMuscles": [
      "forearm-flexors",
      "rhomboids"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "Barbell"
    ],
    "summary": "A shrug variation with the barbell held behind the body, targeting the trapezius.",
    "keyCue": "Stand holding a barbell behind your back with an overhand grip",
    "steps": [
      "Stand holding a barbell behind your back with an overhand grip.",
      "Keep your arms straight and chest up.",
      "Shrug your shoulders straight up toward your ears.",
      "Pause and squeeze at the top.",
      "Lower under control and repeat."
    ],
    "tips": [
      "Lift straight up and down without rolling the shoulders.",
      "Avoid bending your elbows to heave the weight higher.",
      "Stand tall with a neutral neck and look straight ahead."
    ],
    "contentSource": "repdb",
    "repdbImageId": "behind-the-back-barbell-shrug"
  },
  {
    "id": "cable-upright-row",
    "name": "Cable Upright Row",
    "primaryMuscles": [
      "lateral-deltoid",
      "trapezius"
    ],
    "secondaryMuscles": [
      "anterior-deltoid",
      "biceps-brachii"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "Cable"
    ],
    "summary": "An upright row performed with a cable for constant tension on the lateral deltoids and traps.",
    "keyCue": "Stand in front of a cable machine and grip a straight bar or rope at thigh height",
    "steps": [
      "Stand in front of a cable machine and grip a straight bar or rope at thigh height.",
      "Pull the bar up toward your chin, leading with your elbows.",
      "Lower under control.",
      "Repeat."
    ],
    "tips": [
      "Keep elbows higher than your wrists.",
      "Avoid shrugging excessively."
    ],
    "contentSource": "repdb",
    "repdbImageId": "cable-upright-row"
  },
  {
    "id": "bodyweight-lateral-raise",
    "name": "Bodyweight Lateral Raise",
    "primaryMuscles": [
      "lateral-deltoid"
    ],
    "secondaryMuscles": [
      "anterior-deltoid",
      "trapezius"
    ],
    "difficulty": "beginner",
    "equipment": [
      "Bodyweight"
    ],
    "summary": "A shoulder isolation movement performed without equipment to develop lateral deltoid width.",
    "keyCue": "Stand upright with arms hanging at your sides",
    "steps": [
      "Stand upright with arms hanging at your sides.",
      "Raise both arms out to the sides with a slight elbow bend until parallel with the floor.",
      "Pause briefly at the top.",
      "Lower slowly back to the starting position.",
      "Repeat for the desired reps."
    ],
    "tips": [
      "Lead with your elbows, not your hands.",
      "Avoid shrugging your shoulders at the top.",
      "Control the descent to maximize time under tension."
    ],
    "contentSource": "repdb",
    "repdbImageId": "bodyweight-lateral-raise"
  },
  {
    "id": "behind-the-neck-press",
    "name": "Behind the Neck Press",
    "primaryMuscles": [
      "anterior-deltoid",
      "lateral-deltoid"
    ],
    "secondaryMuscles": [
      "trapezius",
      "triceps-brachii"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "Barbell"
    ],
    "summary": "An overhead press performed with the barbell starting behind the neck, emphasizing the front and side deltoids.",
    "keyCue": "Sit or stand with a barbell resting on your upper traps behind your neck",
    "steps": [
      "Sit or stand with a barbell resting on your upper traps behind your neck.",
      "Grip the bar wider than shoulder width.",
      "Press the bar straight up overhead until your arms are extended.",
      "Lower the bar back to the starting position under control.",
      "Repeat for the desired number of reps."
    ],
    "tips": [
      "Lower the bar only as far as your shoulders allow comfortably.",
      "Keep your forearms vertical under the bar throughout the press.",
      "Brace your core to avoid arching the lower back overhead."
    ],
    "contentSource": "repdb",
    "repdbImageId": "behind-the-neck-press"
  },
  {
    "id": "bicycle-crunch",
    "name": "Bicycle Crunch",
    "primaryMuscles": [
      "obliques",
      "rectus-abdominis"
    ],
    "secondaryMuscles": [],
    "difficulty": "beginner",
    "equipment": [
      "Bodyweight"
    ],
    "summary": "A dynamic crunch variation targeting both the rectus abdominis and obliques.",
    "keyCue": "Lie on your back with hands behind your head and legs raised",
    "steps": [
      "Lie on your back with hands behind your head and legs raised.",
      "Bring one knee toward your chest while rotating your torso to meet it with the opposite elbow.",
      "Extend that leg while bringing the other knee in.",
      "Continue alternating in a pedaling motion.",
      "Repeat."
    ],
    "tips": [
      "Avoid pulling on your neck with your hands.",
      "Lead the rotation with your shoulder, not your elbow.",
      "Move slowly and deliberately rather than racing through reps."
    ],
    "contentSource": "repdb",
    "repdbImageId": "bicycle-crunch"
  },
  {
    "id": "dumbbell-side-bend",
    "name": "Dumbbell Side Bend",
    "primaryMuscles": [
      "obliques"
    ],
    "secondaryMuscles": [
      "erector-spinae",
      "transverse-abdominis"
    ],
    "difficulty": "beginner",
    "equipment": [
      "Dumbbells"
    ],
    "summary": "A standing oblique isolation exercise using a dumbbell to develop lateral core strength and stability.",
    "keyCue": "Stand upright holding a dumbbell in one hand at your side",
    "steps": [
      "Stand upright holding a dumbbell in one hand at your side.",
      "Keep the opposite hand on your hip or behind your head.",
      "Bend laterally toward the dumbbell side, lowering it along your thigh.",
      "Return to upright, then bend to the opposite side using only your obliques.",
      "Complete all reps per side."
    ],
    "tips": [
      "Avoid leaning forward or backward — move strictly sideways.",
      "Use a controlled tempo in both directions.",
      "Keep the weight close to your leg throughout."
    ],
    "contentSource": "repdb",
    "repdbImageId": "dumbbell-side-bend",
    "externalMediaId": "Dumbbell_Side_Bend"
  },
  {
    "id": "kettlebell-russian-twist",
    "name": "Kettlebell Russian Twist",
    "primaryMuscles": [
      "obliques"
    ],
    "secondaryMuscles": [
      "rectus-abdominis"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "Kettlebell"
    ],
    "summary": "A seated rotational core exercise twisting a kettlebell from side to side with the feet lifted.",
    "keyCue": "Sit on the floor with your knees bent and feet lifted off the ground",
    "steps": [
      "Sit on the floor with your knees bent and feet lifted off the ground.",
      "Hold a kettlebell with both hands in front of your chest.",
      "Lean back slightly to engage your core.",
      "Rotate your torso to one side, bringing the kettlebell next to your hip.",
      "Rotate to the opposite side in a controlled motion.",
      "Repeat for the desired number of reps."
    ],
    "tips": [
      "Rotate your whole torso, not just your arms.",
      "Keep your spine tall instead of slumping as you twist.",
      "Keep your legs still as your torso moves side to side."
    ],
    "contentSource": "repdb",
    "repdbImageId": "kettlebell-russian-twist"
  },
  {
    "id": "kettlebell-windmills",
    "name": "Kettlebell Windmills",
    "primaryMuscles": [
      "adductors",
      "anterior-deltoid",
      "obliques"
    ],
    "secondaryMuscles": [
      "erector-spinae",
      "gluteus-maximus",
      "hamstrings"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "Kettlebell"
    ],
    "summary": "A kettlebell exercise hinging sideways under a locked-out overhead weight, training oblique strength and shoulder stability.",
    "keyCue": "Stand holding a kettlebell locked out overhead in one hand",
    "steps": [
      "Stand holding a kettlebell locked out overhead in one hand.",
      "Turn your feet about 45 degrees away from the working arm.",
      "Keeping the kettlebell up, hinge at the hips sideways.",
      "Reach your opposite hand down toward your foot.",
      "Drive your hips back to stand up tall.",
      "Complete reps on one side, then switch."
    ],
    "tips": [
      "Keep your eyes on the kettlebell throughout the movement.",
      "Push your hips out to the side instead of rounding your spine.",
      "Start light until the hinge pattern feels stable and controlled."
    ],
    "contentSource": "repdb",
    "repdbImageId": "kettlebell-windmills"
  },
  {
    "id": "russian-twist",
    "name": "Russian Twist",
    "primaryMuscles": [
      "obliques",
      "rectus-abdominis"
    ],
    "secondaryMuscles": [],
    "difficulty": "beginner",
    "equipment": [
      "Bodyweight"
    ],
    "summary": "A rotational core exercise targeting the obliques.",
    "keyCue": "Sit on the floor with knees bent, lean back slightly",
    "steps": [
      "Sit on the floor with knees bent, lean back slightly.",
      "Hold your hands together or hold a weight at chest level.",
      "Rotate your torso to one side, then the other.",
      "Keep your core braced throughout.",
      "Repeat."
    ],
    "tips": [
      "Rotate from the torso rather than just swinging the arms.",
      "Keep your chest lifted and your spine long as you twist.",
      "Move at a controlled tempo instead of racing through reps."
    ],
    "contentSource": "repdb",
    "repdbImageId": "russian-twist",
    "externalMediaId": "Russian_Twist"
  },
  {
    "id": "crunches",
    "name": "Crunches",
    "primaryMuscles": [
      "rectus-abdominis"
    ],
    "secondaryMuscles": [
      "obliques"
    ],
    "difficulty": "beginner",
    "equipment": [
      "Bodyweight"
    ],
    "summary": "A basic abdominal exercise focusing on the rectus abdominis.",
    "keyCue": "Lie on your back with knees bent and hands behind your head",
    "steps": [
      "Lie on your back with knees bent and hands behind your head.",
      "Curl your upper body toward your knees, lifting your shoulder blades off the floor.",
      "Squeeze your abs at the top.",
      "Lower with control.",
      "Repeat."
    ],
    "tips": [
      "Avoid pulling on your neck with your hands.",
      "Exhale as you curl up and inhale on the way down.",
      "Keep your lower back pressed into the floor throughout."
    ],
    "contentSource": "repdb",
    "repdbImageId": "crunches",
    "externalMediaId": "Crunches"
  },
  {
    "id": "plank",
    "name": "Plank",
    "primaryMuscles": [
      "rectus-abdominis",
      "transverse-abdominis"
    ],
    "secondaryMuscles": [
      "erector-spinae"
    ],
    "difficulty": "beginner",
    "equipment": [
      "Bodyweight"
    ],
    "summary": "An isometric core exercise that strengthens the entire midsection.",
    "keyCue": "Place your forearms on the floor with elbows under your shoulders",
    "steps": [
      "Place your forearms on the floor with elbows under your shoulders.",
      "Extend your legs back and rise onto your toes.",
      "Keep your body in a straight line from head to heels.",
      "Brace your core and squeeze your glutes.",
      "Hold the position for the desired duration.",
      "Lower your knees to exit the hold."
    ],
    "tips": [
      "Do not let your hips sag or pike up.",
      "Squeeze your glutes and quads."
    ],
    "contentSource": "repdb",
    "repdbImageId": "plank",
    "externalMediaId": "Plank"
  },
  {
    "id": "captains-chair-knee-raise",
    "name": "Captain's Chair Knee Raise",
    "primaryMuscles": [
      "rectus-abdominis"
    ],
    "secondaryMuscles": [
      "obliques",
      "transverse-abdominis"
    ],
    "difficulty": "beginner",
    "equipment": [
      "Bodyweight"
    ],
    "summary": "A bodyweight core exercise performed on a captain's chair that targets the lower abs and hip flexors.",
    "keyCue": "Position yourself in the captain's chair with your back flat against the pad and forearms on the armrests",
    "steps": [
      "Position yourself in the captain's chair with your back flat against the pad and forearms on the armrests.",
      "Let your legs hang straight down.",
      "Engage your core and raise your knees toward your chest.",
      "Hold briefly at the top, then lower slowly to the starting position.",
      "Repeat for the desired reps."
    ],
    "tips": [
      "Avoid swinging the legs for momentum.",
      "Exhale as you raise your knees.",
      "Keep your back pressed against the pad throughout."
    ],
    "contentSource": "repdb",
    "repdbImageId": "captains-chair-knee-raise"
  },
  {
    "id": "leg-curl",
    "name": "Lying Leg Curl",
    "primaryMuscles": [
      "hamstrings"
    ],
    "secondaryMuscles": [
      "gastrocnemius"
    ],
    "difficulty": "beginner",
    "equipment": [
      "Leg curl machine"
    ],
    "summary": "An isolation exercise for the hamstrings using a leg curl machine.",
    "keyCue": "Lie face down on the leg curl machine with ankles under the pad",
    "steps": [
      "Lie face down on the leg curl machine with ankles under the pad.",
      "Curl your heels toward your glutes.",
      "Squeeze your hamstrings at the top.",
      "Lower with control.",
      "Repeat."
    ],
    "tips": [
      "Keep your hips pressed into the bench throughout the set.",
      "Avoid jerking the weight up with your lower back.",
      "Use a full range of motion without letting the stack slam down."
    ],
    "contentSource": "repdb",
    "repdbImageId": "leg-curl",
    "video": {
      "src": "/exercise-media/leg-curl.mp4",
      "poster": "/exercise-media/leg-curl.webp"
    }
  },
  {
    "id": "romanian-deadlift",
    "name": "Romanian Deadlift",
    "primaryMuscles": [
      "gluteus-maximus",
      "hamstrings"
    ],
    "secondaryMuscles": [
      "erector-spinae"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "Barbell"
    ],
    "summary": "A hip-hinge movement emphasizing the hamstrings and glutes.",
    "keyCue": "Stand holding a barbell at hip level with an overhand grip",
    "steps": [
      "Stand holding a barbell at hip level with an overhand grip.",
      "Hinge at the hips, pushing them back while keeping legs nearly straight.",
      "Lower the bar along your legs until you feel a hamstring stretch.",
      "Drive your hips forward to return to standing.",
      "Repeat."
    ],
    "tips": [
      "Keep your spine neutral and avoid rounding the lower back.",
      "Maintain the same slight knee bend for the entire rep.",
      "Go only as deep as your hamstring flexibility allows."
    ],
    "contentSource": "repdb",
    "repdbImageId": "romanian-deadlift",
    "externalMediaId": "Romanian_Deadlift"
  },
  {
    "id": "hammer-curl",
    "name": "Dumbbell Hammer Curl",
    "primaryMuscles": [
      "biceps-brachii",
      "brachialis"
    ],
    "secondaryMuscles": [
      "forearm-flexors"
    ],
    "difficulty": "beginner",
    "equipment": [
      "Dumbbells"
    ],
    "summary": "A bicep curl variation with a neutral grip targeting the brachioradialis.",
    "keyCue": "Stand holding dumbbells at your sides with palms facing each other",
    "steps": [
      "Stand holding dumbbells at your sides with palms facing each other.",
      "Curl the weights up while keeping your palms facing inward.",
      "Squeeze at the top, then lower under control.",
      "Repeat."
    ],
    "tips": [
      "Keep your elbows pinned to your sides throughout.",
      "Keep your wrists straight and rigid throughout the curl.",
      "Avoid leaning back or swinging the weights up."
    ],
    "contentSource": "repdb",
    "repdbImageId": "hammer-curl",
    "video": {
      "src": "/exercise-media/hammer-curl.mp4",
      "poster": "/exercise-media/hammer-curl.webp"
    }
  },
  {
    "id": "db-reverse-curl",
    "name": "Dumbbell Reverse Curl",
    "primaryMuscles": [
      "brachialis",
      "forearm-extensors"
    ],
    "secondaryMuscles": [
      "biceps-brachii"
    ],
    "difficulty": "beginner",
    "equipment": [
      "Dumbbells"
    ],
    "summary": "A curl variation with a pronated grip targeting the brachialis and forearm extensors.",
    "keyCue": "Hold dumbbells with an overhand grip at your sides",
    "steps": [
      "Hold dumbbells with an overhand grip at your sides.",
      "Curl them up to shoulder height.",
      "Lower under control.",
      "Repeat."
    ],
    "tips": [
      "Keep wrists neutral throughout.",
      "Controlled movement is key."
    ],
    "contentSource": "repdb",
    "repdbImageId": "db-reverse-curl"
  },
  {
    "id": "cross-body-hammer-curl",
    "name": "Cross Body Hammer Curl",
    "primaryMuscles": [
      "brachialis",
      "brachioradialis"
    ],
    "secondaryMuscles": [
      "biceps-brachii",
      "forearm-flexors"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "Dumbbells"
    ],
    "summary": "A neutral-grip curl bringing the dumbbell across the body toward the opposite shoulder, emphasizing the brachialis and forearms.",
    "keyCue": "Stand tall holding a dumbbell in each hand with a neutral grip",
    "steps": [
      "Stand tall holding a dumbbell in each hand with a neutral grip.",
      "Curl one dumbbell up across your body toward the opposite shoulder.",
      "Keep your elbow stationary at your side.",
      "Lower under control and repeat on the other side.",
      "Continue alternating for the desired number of reps."
    ],
    "tips": [
      "Keep your elbow pinned at your side throughout the curl.",
      "Avoid swinging your torso to lift the weight.",
      "Lower under control rather than letting the dumbbell drop."
    ],
    "contentSource": "repdb",
    "repdbImageId": "cross-body-hammer-curl",
    "externalMediaId": "Cross_Body_Hammer_Curl"
  },
  {
    "id": "ez-bar-reverse-curl",
    "name": "EZ-Bar Reverse Curl",
    "primaryMuscles": [
      "brachialis",
      "forearm-extensors"
    ],
    "secondaryMuscles": [
      "biceps-brachii"
    ],
    "difficulty": "beginner",
    "equipment": [
      "EZ bar"
    ],
    "summary": "A reverse curl with an EZ-bar targeting the brachialis and forearm extensors with a comfortable grip.",
    "keyCue": "Hold an EZ-bar with an overhand grip",
    "steps": [
      "Hold an EZ-bar with an overhand grip.",
      "Curl the bar up toward your shoulders.",
      "Lower under control.",
      "Repeat."
    ],
    "tips": [
      "Keep elbows close to your torso.",
      "The EZ-bar reduces wrist strain."
    ],
    "contentSource": "repdb",
    "repdbImageId": "ez-bar-reverse-curl"
  },
  {
    "id": "dumbbell-wrist-curl",
    "name": "Dumbbell Wrist Curl",
    "primaryMuscles": [
      "forearm-flexors"
    ],
    "secondaryMuscles": [
      "brachioradialis"
    ],
    "difficulty": "beginner",
    "equipment": [
      "Dumbbells"
    ],
    "summary": "A dumbbell wrist curl that isolates the forearm flexors and trains both arms independently.",
    "keyCue": "Sit on a bench with the forearm resting on the thigh, palm up",
    "steps": [
      "Sit on a bench with the forearm resting on the thigh, palm up.",
      "Hold a dumbbell with the wrist hanging off the knee.",
      "Let the dumbbell roll down to the fingertips.",
      "Curl the dumbbell up by flexing the wrist.",
      "Lower under control. Complete reps per side."
    ],
    "tips": [
      "Move only at the wrist — keep the forearm still.",
      "Roll the dumbbell to the fingertips for full range.",
      "Train both arms with the same load and reps."
    ],
    "contentSource": "repdb",
    "repdbImageId": "dumbbell-wrist-curl"
  },
  {
    "id": "cable-wrist-curl",
    "name": "Cable Wrist Curl",
    "primaryMuscles": [
      "forearm-flexors"
    ],
    "secondaryMuscles": [],
    "difficulty": "intermediate",
    "equipment": [
      "Cable"
    ],
    "summary": "An isolation exercise flexing the wrists against cable resistance to strengthen the forearm flexors.",
    "keyCue": "Attach a straight bar to a low cable pulley",
    "steps": [
      "Attach a straight bar to a low cable pulley.",
      "Kneel or sit with forearms on a bench, palms facing up.",
      "Let your wrists flex off the bench edge.",
      "Curl the bar up by flexing your wrists.",
      "Lower under control and repeat."
    ],
    "tips": [
      "Move only at the wrists; keep your forearms pressed into the bench.",
      "Perform the reps slowly to avoid straining your wrists.",
      "Pause briefly at the top of each rep for a stronger contraction."
    ],
    "contentSource": "repdb",
    "repdbImageId": "cable-wrist-curl",
    "externalMediaId": "Cable_Wrist_Curl"
  },
  {
    "id": "hip-abduction",
    "name": "Machine Hip Abduction",
    "primaryMuscles": [
      "gluteus-medius"
    ],
    "secondaryMuscles": [],
    "difficulty": "beginner",
    "equipment": [
      "Hip abduction machine"
    ],
    "summary": "A machine exercise targeting the outer hip muscles.",
    "keyCue": "Sit in the hip abduction machine with pads against your outer thighs",
    "steps": [
      "Sit in the hip abduction machine with pads against your outer thighs.",
      "Push your legs apart against the resistance.",
      "Hold briefly at the widest point.",
      "Return to the starting position with control.",
      "Repeat."
    ],
    "tips": [
      "Sit tall and keep your back against the pad.",
      "Don't let the weight stack slam down between reps.",
      "Choose a resistance that allows a full range of motion."
    ],
    "contentSource": "repdb",
    "repdbImageId": "hip-abduction"
  },
  {
    "id": "side-lying-hip-abduction",
    "name": "Side-Lying Hip Abduction",
    "primaryMuscles": [
      "gluteus-medius"
    ],
    "secondaryMuscles": [],
    "difficulty": "beginner",
    "equipment": [
      "Bodyweight"
    ],
    "summary": "A bodyweight isolation exercise targeting the gluteus medius and hip abductors.",
    "keyCue": "Lie on your side with legs stacked",
    "steps": [
      "Lie on your side with legs stacked.",
      "Keep the bottom leg slightly bent.",
      "Raise the top leg toward the ceiling.",
      "Lower under control.",
      "Repeat on both sides."
    ],
    "tips": [
      "Keep hips stacked throughout.",
      "Avoid tilting the pelvis."
    ],
    "contentSource": "repdb",
    "repdbImageId": "side-lying-hip-abduction"
  },
  {
    "id": "clamshells",
    "name": "Clamshells",
    "primaryMuscles": [
      "gluteus-medius"
    ],
    "secondaryMuscles": [
      "gluteus-maximus"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "Bodyweight"
    ],
    "summary": "A side-lying hip exercise opening the top knee against gravity to activate the gluteus medius.",
    "keyCue": "Lie on your side with knees bent and stacked on top of each other",
    "steps": [
      "Lie on your side with knees bent and stacked on top of each other.",
      "Keep your feet together and hips stacked.",
      "Open your top knee toward the ceiling without rotating your hips.",
      "Squeeze your outer glute at the top.",
      "Lower under control. Complete reps on one side, then switch."
    ],
    "tips": [
      "Place a hand on your top hip to check for unwanted rolling.",
      "Keep the movement small and controlled rather than forcing the knee high.",
      "Rest your head on your lower arm to keep your spine neutral."
    ],
    "contentSource": "repdb",
    "repdbImageId": "clamshells"
  },
  {
    "id": "reverse-curl",
    "name": "Reverse Curl",
    "primaryMuscles": [
      "brachialis",
      "forearm-extensors"
    ],
    "secondaryMuscles": [
      "biceps-brachii"
    ],
    "difficulty": "beginner",
    "equipment": [
      "Barbell"
    ],
    "summary": "A barbell curl with an overhand grip targeting the brachialis and forearm extensors.",
    "keyCue": "Stand and hold a barbell with an overhand grip",
    "steps": [
      "Stand and hold a barbell with an overhand grip.",
      "Curl the bar up toward your shoulders.",
      "Lower under control.",
      "Repeat."
    ],
    "tips": [
      "Keep wrists straight.",
      "Move through a full range of motion."
    ],
    "contentSource": "repdb",
    "repdbImageId": "reverse-curl"
  },
  {
    "id": "dead-bug",
    "name": "Dead Bug",
    "primaryMuscles": [
      "rectus-abdominis",
      "transverse-abdominis"
    ],
    "secondaryMuscles": [],
    "difficulty": "beginner",
    "equipment": [
      "Bodyweight"
    ],
    "summary": "A supine core exercise coordinating opposite limb extension to train deep core stability.",
    "keyCue": "Lie on your back with arms extended toward the ceiling and knees at 90 degrees",
    "steps": [
      "Lie on your back with arms extended toward the ceiling and knees at 90 degrees.",
      "Lower your right arm and left leg toward the floor while keeping the lower back pressed down.",
      "Return to start.",
      "Repeat on the other side.",
      "Alternate."
    ],
    "tips": [
      "Press your lower back into the floor at all times.",
      "Move slowly."
    ],
    "contentSource": "repdb",
    "repdbImageId": "dead-bug",
    "externalMediaId": "Dead_Bug"
  },
  {
    "id": "high-plank",
    "name": "High Plank",
    "primaryMuscles": [
      "rectus-abdominis",
      "transverse-abdominis"
    ],
    "secondaryMuscles": [
      "erector-spinae",
      "obliques"
    ],
    "difficulty": "beginner",
    "equipment": [
      "Bodyweight"
    ],
    "summary": "A plank variation with arms fully extended in a push-up position.",
    "keyCue": "Start in a push-up position with arms fully extended",
    "steps": [
      "Start in a push-up position with arms fully extended.",
      "Keep your body in a straight line from head to heels.",
      "Brace your core and hold the position.",
      "Breathe steadily throughout."
    ],
    "tips": [
      "Stack your shoulders directly above your wrists.",
      "Squeeze your glutes to keep your hips from sagging.",
      "Push the floor away to avoid sinking between your shoulder blades."
    ],
    "contentSource": "repdb",
    "repdbImageId": "high-plank"
  },
  {
    "id": "side-plank",
    "name": "Side Plank",
    "primaryMuscles": [
      "obliques",
      "transverse-abdominis"
    ],
    "secondaryMuscles": [
      "gluteus-medius",
      "rectus-abdominis"
    ],
    "difficulty": "beginner",
    "equipment": [
      "Bodyweight"
    ],
    "summary": "A lateral plank variation targeting the obliques and lateral core.",
    "keyCue": "Lie on your side with your forearm on the floor, elbow under your shoulder",
    "steps": [
      "Lie on your side with your forearm on the floor, elbow under your shoulder.",
      "Lift your hips off the floor, forming a straight line from head to feet.",
      "Hold the position, keeping your core tight.",
      "Breathe steadily.",
      "Repeat on both sides."
    ],
    "tips": [
      "Don't let your top shoulder roll forward during the hold.",
      "Push the floor away through the forearm rather than sinking into the shoulder.",
      "Keep your head in line with your spine."
    ],
    "contentSource": "repdb",
    "repdbImageId": "side-plank"
  },
  {
    "id": "seated-calf-raise",
    "name": "Seated Calf Raise",
    "primaryMuscles": [
      "soleus"
    ],
    "secondaryMuscles": [
      "gastrocnemius"
    ],
    "difficulty": "beginner",
    "equipment": [
      "seated calf raise machine"
    ],
    "summary": "A machine calf raise performed seated to specifically target the soleus muscle.",
    "keyCue": "Sit at a calf raise machine with the pads resting on your thighs",
    "steps": [
      "Sit at a calf raise machine with the pads resting on your thighs.",
      "Lower your heels as far as possible.",
      "Raise up onto your toes.",
      "Lower under control.",
      "Repeat."
    ],
    "tips": [
      "Seated position pre-stretches the soleus.",
      "Use a full range of motion."
    ],
    "contentSource": "repdb",
    "repdbImageId": "seated-calf-raise",
    "externalMediaId": "Seated_Calf_Raise"
  },
  {
    "id": "hack-squat-calf-raise",
    "name": "Hack Squat Calf Raise",
    "primaryMuscles": [
      "gastrocnemius",
      "soleus"
    ],
    "secondaryMuscles": [],
    "difficulty": "intermediate",
    "equipment": [
      "Hack squat"
    ],
    "summary": "A calf raise performed in the hack squat machine, loading the calves heavily without balancing a bar.",
    "keyCue": "Load yourself into a hack squat machine with shoulders under the pads",
    "steps": [
      "Load yourself into a hack squat machine with shoulders under the pads.",
      "Place the balls of your feet on the platform with heels hanging off.",
      "Keep your legs straight with a slight knee bend.",
      "Press through the balls of your feet to raise your heels.",
      "Lower your heels back below the platform for a stretch.",
      "Repeat for the desired number of reps."
    ],
    "tips": [
      "Rise as high onto the balls of your feet as possible.",
      "Pause in the bottom stretch instead of bouncing out of it.",
      "Keep your knees straight but not locked to keep tension on the calves."
    ],
    "contentSource": "repdb",
    "repdbImageId": "hack-squat-calf-raise"
  },
  {
    "id": "dumbbell-face-pull",
    "name": "Dumbbell Face Pull",
    "primaryMuscles": [
      "posterior-deltoid",
      "rhomboids"
    ],
    "secondaryMuscles": [
      "biceps-brachii",
      "trapezius"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "Dumbbells"
    ],
    "summary": "A rear-delt and upper-back exercise performed by pulling dumbbells toward the face with a wide elbow path.",
    "keyCue": "Stand or sit holding a dumbbell in each hand with arms extended forward",
    "steps": [
      "Stand or sit holding a dumbbell in each hand with arms extended forward.",
      "Bend your elbows and pull the dumbbells toward your face.",
      "Flare your elbows out wide to shoulder height.",
      "Squeeze your rear delts and upper back at the peak.",
      "Lower the dumbbells back under control.",
      "Repeat for the desired number of reps."
    ],
    "tips": [
      "Lead with your elbows, not your hands.",
      "Keep your upper arms roughly parallel to the floor.",
      "Use a lighter weight to prioritize form over load."
    ],
    "contentSource": "repdb",
    "repdbImageId": "dumbbell-face-pull"
  },
  {
    "id": "ring-face-pull",
    "name": "Ring Face Pull",
    "primaryMuscles": [
      "posterior-deltoid",
      "rhomboids"
    ],
    "secondaryMuscles": [
      "trapezius"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "rings"
    ],
    "summary": "A face pull using gymnastic rings for adjustable resistance and improved shoulder health.",
    "keyCue": "Grip the rings and lean back so your body is at an angle",
    "steps": [
      "Grip the rings and lean back so your body is at an angle.",
      "Pull the rings toward your face, flaring elbows to the sides.",
      "Hold briefly, then return.",
      "Repeat."
    ],
    "tips": [
      "Adjust your body angle to control difficulty.",
      "Externally rotate your arms at the top."
    ],
    "contentSource": "repdb",
    "repdbImageId": "ring-face-pull"
  },
  {
    "id": "hip-adduction",
    "name": "Hip Adduction",
    "primaryMuscles": [
      "adductors"
    ],
    "secondaryMuscles": [],
    "difficulty": "intermediate",
    "equipment": [
      "Hip adduction machine"
    ],
    "summary": "A machine exercise pressing the legs together against resistance, isolating and strengthening the inner-thigh adductors.",
    "keyCue": "Sit on the hip adduction machine with your back against the pad",
    "steps": [
      "Sit on the hip adduction machine with your back against the pad.",
      "Place your legs against the pads with the machine set to a comfortable stretch.",
      "Squeeze your legs together until the pads meet in the middle.",
      "Hold the squeeze briefly in the fully closed position.",
      "Let your legs open back out under control to the start.",
      "Repeat for the desired number of reps."
    ],
    "tips": [
      "Choose a start width that stretches without straining your groin.",
      "Move through the whole range at an even, controlled speed.",
      "Do not let the weight stack slam down as your legs open back out."
    ],
    "contentSource": "repdb",
    "repdbImageId": "hip-adduction"
  },
  {
    "id": "incline-push-ups",
    "name": "Incline Push-Up",
    "primaryMuscles": [
      "pectoralis-major-clavicular"
    ],
    "secondaryMuscles": [
      "anterior-deltoid",
      "triceps-brachii"
    ],
    "difficulty": "beginner",
    "equipment": [
      "Bodyweight"
    ],
    "summary": "A beginner-friendly push-up variation with hands elevated on a bench or step.",
    "keyCue": "Place your hands on a bench or elevated surface, shoulder-width apart",
    "steps": [
      "Place your hands on a bench or elevated surface, shoulder-width apart.",
      "Extend your legs behind you into a plank position.",
      "Lower your chest toward the bench by bending your elbows.",
      "Push back up to the starting position.",
      "Repeat."
    ],
    "tips": [
      "Check that the elevated surface is stable before starting.",
      "Keep your elbows tucked rather than flared out wide.",
      "Progress to a lower surface as you get stronger."
    ],
    "contentSource": "repdb",
    "repdbImageId": "incline-push-ups",
    "externalMediaId": "Incline_Push-Up"
  },
  {
    "id": "incline-bench-press",
    "name": "Incline Barbell Bench Press",
    "primaryMuscles": [
      "pectoralis-major-clavicular"
    ],
    "secondaryMuscles": [
      "anterior-deltoid",
      "triceps-brachii"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "Barbell"
    ],
    "summary": "A barbell pressing movement on an incline bench targeting the upper chest.",
    "keyCue": "Lie on an incline bench set to 30-45 degrees",
    "steps": [
      "Lie on an incline bench set to 30-45 degrees.",
      "Grip the bar slightly wider than shoulder-width and unrack.",
      "Lower the bar to your upper chest.",
      "Press the bar back up to full extension.",
      "Repeat."
    ],
    "tips": [
      "Keep your shoulder blades pinched together against the bench.",
      "Lower the bar without bouncing it off your chest.",
      "Keep your feet planted and your glutes on the bench."
    ],
    "contentSource": "repdb",
    "repdbImageId": "incline-bench-press"
  },
  {
    "id": "incline-dumbbell-fly",
    "name": "Incline Dumbbell Fly",
    "primaryMuscles": [
      "pectoralis-major-clavicular"
    ],
    "secondaryMuscles": [
      "anterior-deltoid",
      "biceps-brachii"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "Dumbbells"
    ],
    "summary": "An incline isolation exercise opening dumbbells in a wide arc, stretching and targeting the upper chest.",
    "keyCue": "Lie back on an incline bench holding dumbbells above your chest",
    "steps": [
      "Lie back on an incline bench holding dumbbells above your chest.",
      "Press the dumbbells up with palms facing each other.",
      "Maintain a slight bend in your elbows throughout.",
      "Lower the dumbbells in a wide arc until you feel a chest stretch.",
      "Squeeze your chest to bring the dumbbells back together.",
      "Repeat for the desired number of reps."
    ],
    "tips": [
      "Keep a fixed slight bend in your elbows throughout.",
      "Lower only as far as a comfortable chest stretch allows.",
      "Squeeze your chest to bring the dumbbells back together."
    ],
    "contentSource": "repdb",
    "repdbImageId": "incline-dumbbell-fly"
  },
  {
    "id": "incline-db-press",
    "name": "Incline Dumbbell Press",
    "primaryMuscles": [
      "pectoralis-major-clavicular"
    ],
    "secondaryMuscles": [
      "anterior-deltoid",
      "triceps-brachii"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "Dumbbells"
    ],
    "summary": "An incline pressing movement emphasizing the upper chest.",
    "keyCue": "Set bench to 30-degree incline and sit back with dumbbells at shoulder level",
    "steps": [
      "Set bench to 30-degree incline and sit back with dumbbells at shoulder level.",
      "Press dumbbells up and together until arms are fully extended.",
      "Lower dumbbells back to shoulder level with control.",
      "Repeat."
    ],
    "tips": [
      "Keep your wrists stacked directly over your elbows.",
      "Press up without banging the dumbbells together at the top.",
      "Keep your shoulder blades pulled back against the bench."
    ],
    "contentSource": "repdb",
    "repdbImageId": "incline-db-press",
    "externalMediaId": "Incline_Dumbbell_Press"
  },
  {
    "id": "incline-bench-ez-bar-press",
    "name": "Incline EZ-Bar Bench Press",
    "primaryMuscles": [
      "pectoralis-major-clavicular"
    ],
    "secondaryMuscles": [
      "anterior-deltoid",
      "triceps-brachii"
    ],
    "difficulty": "intermediate",
    "equipment": [
      "EZ bar"
    ],
    "summary": "An incline press with an EZ-bar targeting the upper chest with a joint-friendly grip.",
    "keyCue": "Set bench to 30–45 degrees. Grip the EZ-bar with hands on the angled sections",
    "steps": [
      "Set bench to 30–45 degrees. Grip the EZ-bar with hands on the angled sections.",
      "Lower the bar to your upper chest.",
      "Press back up to full extension.",
      "Repeat."
    ],
    "tips": [
      "The incline shifts emphasis to the upper pectorals.",
      "Control the descent to avoid shoulder strain."
    ],
    "contentSource": "repdb",
    "repdbImageId": "incline-bench-ez-bar-press"
  }
];
